// EventGo service worker — generated by _src/build.js (do not edit by hand).
'use strict';
var VERSION = '41bd053598';
var STATIC = 'eventgo-static-' + VERSION;
var RUNTIME = 'eventgo-runtime';
var PRECACHE = ["index.html","explorer.html","carte.html","evenement.html","reservation.html","confirmation.html","billets.html","billet.html","rappels.html","favoris.html","profil.html","offline.html","assets/site.css","assets/data.js","assets/core.js","assets/pages.js","assets/favicon.svg","manifest.webmanifest","assets/icons/icon-192.png","assets/icons/icon-512.png","assets/icons/maskable-512.png","assets/icons/apple-touch-icon.png","assets/img/concert.jpg","assets/img/atelier.jpg","assets/img/rencontre.jpg","assets/img/exposition.jpg","assets/img/educatif.jpg","assets/img/culturel.jpg","assets/img/institutionnel.jpg","assets/img/orange-money-logo.png","assets/img/mtn-logo.svg"];
var THIRD_PARTY = /(^|\.)(fonts\.googleapis\.com|fonts\.gstatic\.com|unpkg\.com|cdn\.jsdelivr\.net)$/;

self.addEventListener('install', function (e) {
  e.waitUntil(caches.open(STATIC).then(function (c) { return c.addAll(PRECACHE); }).then(function () { return self.skipWaiting(); }));
});

self.addEventListener('activate', function (e) {
  e.waitUntil(caches.keys().then(function (keys) {
    return Promise.all(keys.filter(function (k) { return k.indexOf('eventgo-static-') === 0 && k !== STATIC; }).map(function (k) { return caches.delete(k); }));
  }).then(function () { return self.clients.claim(); }));
});

function pageKey(url) { var p = url.pathname; if (p.charAt(p.length - 1) === '/') p += 'index.html'; return url.origin + p; }

function networkFirst(req) {
  var url = new URL(req.url), key = pageKey(url);
  return fetch(req).then(function (res) {
    if (res && res.ok) { var copy = res.clone(); caches.open(STATIC).then(function (c) { c.put(key, copy); }); }
    return res;
  }).catch(function () {
    return caches.match(key).then(function (hit) { return hit || caches.match(new URL('offline.html', self.registration.scope).href); });
  });
}

function staleWhileRevalidate(req, cacheName) {
  return caches.open(cacheName).then(function (cache) {
    return cache.match(req).then(function (hit) {
      var net = fetch(req).then(function (res) { if (res && (res.ok || res.type === 'opaque')) cache.put(req, res.clone()); return res; }).catch(function () { return hit; });
      return hit || net;
    });
  });
}

self.addEventListener('fetch', function (e) {
  var req = e.request;
  if (req.method !== 'GET') return;
  var url = new URL(req.url);
  if (/tile\.openstreetmap\.org$/.test(url.hostname)) return; // map tiles: network only
  if (req.mode === 'navigate') { if (url.origin === self.location.origin) e.respondWith(networkFirst(req)); return; }
  if (url.origin === self.location.origin) {
    if (/\/(prototype|wireframe)\//.test(url.pathname)) return;
    e.respondWith(caches.match(req).then(function (hit) { return hit || staleWhileRevalidate(req, STATIC); }).then(function (res) {
      // refresh in background for code files so updates arrive on next visit
      return res;
    }));
    return;
  }
  if (THIRD_PARTY.test(url.hostname)) e.respondWith(staleWhileRevalidate(req, RUNTIME));
});
